name: Move Closed Issues to DONE

on:
  issues:
    types:
      - closed

jobs:
  move_issue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;
            const projectColumnName = 'Issues terminados'; // Replace with your project board column name

            const issue = await github.issues.getIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });

            const columnId = issue.data.project_column.id;

            await github.projects.moveCard({
              card_id: issue.data.id,
              column_id: columnId
            });