name: Mover Pull Requests Cerrados a DONE

on:
  pull_request:
    types:
      - closed

jobs:
  mover_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const numeroPullRequest = context.payload.pull_request.number;
            const nombreColumnaProyecto = 'Pull Requests terminados'; // Reemplácese con el nombre de la columna de su tablero de proyectos

            const pullRequest = await github.pulls.get(context.repo.owner, context.repo.repo, numeroPullRequest);

            if (pullRequest.data.project_column) { // Verifica si el pull request está asociado a una columna del proyecto
              const idColumna = pullRequest.data.project_column.id;

              await github.projects.moveCard({
                card_id: pullRequest.data.id,
                column_id: idColumna
              });
            } else {
              console.log("El pull request no está asociado a una columna del proyecto. Ignorando...");
            }

