name: Move Closed Issues to DONE

on:
  pull_request:
    types:
      - closed

jobs:
  move_issue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pullRequestNumber = context.payload.pull_request.number;
            const projectColumnName = 'Pull Requests terminados'; // Replace with your project board column name

            const pullRequest = await github.pulls.get(context.repo.owner, context.repo.repo, pullRequestNumber);

            const columnId = pullRequest.data.project_column.id;

            await github.projects.moveCard({
              card_id: pullRequest.data.id,
              column_id: columnId
            });
